name: Render PlantUML Diagrams

on:
  push:
    paths:
      - 'docs/architecture/**/*.puml'
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Render all .puml to .png
        uses: grassedge/generate-plantuml-action@v1.5

      - name: Commit rendered diagrams
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/architecture/**/*.png
          git commit -m "update rendered diagrams" || echo "no changes"
          git push
