name: Render Structurizr Diagrams

on:
  push:
    branches: [ main ]
    paths:
      - "docs/architecture/**"
  workflow_dispatch: # optional: manuelles Triggern

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Render Structurizr diagrams
        uses: structurizr/structurizr-render-action@v1
        with:
          structurizr_dsl_path: docs/architecture/campus-app.dsl
          output_path: docs/architecture/diagrams
          # optional:
          output_formats: "png,svg" # Standard ist png
