name: Generate C4 Diagrams

on:
  push:
    branches: [ main ]

jobs:
  structurizr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. DSL -> JSON
      - name: Export Structurizr workspace (JSON)
        uses: gilbertotcc/structurizr-action@v1
        with:
          args: 'export -workspace docs/architecture/campus-app.dsl -format json -output docs/architecture'

      # 2. JSON -> PNG
      - name: Render PNG diagrams
        uses: pleimann/structurizr@v1
        with:
          workspace: docs/architecture/workspace.json
          output-dir: docs/architecture/diagrams

      # 3. Commit results
      - name: Commit generated diagrams
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add docs/architecture/diagrams
          git commit -m "Update diagrams" || echo "No changes"
          git push
