 - name: Structurizr CLI
  # You may pin to the exact commit or the version.
  # uses: gilbertotcc/structurizr-action@ec4b973d57fb0c4555feec4df1706613dcf1a4c3
  uses: gilbertotcc/structurizr-action@latest
  with:
    # Arguments for Structurizr CLI
    args: 'export -workspace docs/architecture/campus-app.dsl -format png -output docs/architecture/diagrams' # default is 
