name: Generate C4 Diagrams

on:
  push:
    paths:
      - 'docs/architecture/**/*.dsl'

jobs:
  structurizr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download latest Structurizr CLI
        run: |
          # URL des neuesten .zip Assets holen
          URL=$(curl -s https://api.github.com/repos/structurizr/cli/releases/latest \
            | grep "browser_download_url.*zip" \
            | cut -d '"' -f 4)
          echo "Downloading: $URL"
          curl -L $URL -o structurizr-cli.zip

          mkdir structurizr-cli
          unzip structurizr-cli.zip -d structurizr-cli

      - name: Export diagrams
        run: |
          JAR=$(find structurizr-cli -name "structurizr-cli-*.jar")
          echo "Using JAR: $JAR"
          java -jar $JAR \
            export -workspace docs/architecture/campus-app.dsl \
            -format plantuml \
            -output docs/architecture/diagrams

      - name: Commit generated diagrams
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add docs/architecture/diagrams
          git commit -m "Update diagrams" || echo "No changes"
          git push
