name: Generate C4 Diagrams

on:
  push:
    paths:
      - 'docs/architecture/**/*.dsl'

jobs:
  structurizr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download latest Structurizr CLI
        run: |
          # URL des neuesten .zip Assets aus dem Release holen
          URL=$(curl -s https://api.github.com/repos/structurizr/cli/releases/latest \
            | grep "browser_download_url.*zip" \
            | cut -d '"' -f 4)
          echo "Downloading: $URL"
          curl -L $URL -o structurizr-cli.zip

          mkdir structurizr-cli
          unzip structurizr-cli.zip -d structurizr-cli

      - name: Debug list extracted files
        run: |
          echo "📂 Inhalt von structurizr-cli nach unzip:"
          ls -R structurizr-cli

      - name: Export diagrams as PNG
        run: |
          # JAR robust finden
          JAR=$(find structurizr-cli -maxdepth 3 -type f -name "structurizr-cli-*.jar" | head -n 1)
          echo "Using JAR: $JAR"

          if [ -z "$JAR" ]; then
